# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be2605fb51e683eb1920bc0e65b4d26b062d5a479f9b625917edaff8709eba1fbb84afededa7e9237fcbc659c784cc5c5d84d3e599a2e0fe9484d8fbd719ac57

test:
  secret_key_base: 7390735746ae965f69e09f545487a03359da30efe67fdd5e15a435fd572ed8857aaa96eb81675d710c133a7e0014df4c1d8bb47bd3e63a7b4ba179564e544342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
